
title: My Resume
url: 'www.22steps.io'
baseurl: '/SidCV' #change it according to your repository name



# Profile information
yourname: Siddaram Hebbal  ## put your name
title: 'Web Application Dev &amp; WEB DESIGNER'  ## your title
location: Karnataka , INDIA


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
